/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-06-08 11:25:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/yasir/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1744455662615L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sign Up - ML Betting</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"navbar-brand\">\r\n");
      out.write("                <img src=\"https://via.placeholder.com/40x40/6C5CE7/FFFFFF?text=ML\" alt=\"ML Betting\">\r\n");
      out.write("                ML Betting\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/matches/upcoming\" class=\"nav-link\">Matches</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"nav-link\">Login</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" class=\"nav-link active\">Sign Up</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Registration Form -->\r\n");
      out.write("    <section class=\"container\" style=\"max-width: 600px; margin-top: 4rem; margin-bottom: 4rem;\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header text-center\">\r\n");
      out.write("                <h2 style=\"margin: 0;\">Create Your Account</h2>\r\n");
      out.write("                <p style=\"margin: 0.5rem 0 0 0; color: var(--text-secondary);\">Join thousands of Mobile Legends fans</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <!-- Display error message if any -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Welcome Bonus Alert -->\r\n");
      out.write("                <div class=\"alert alert-success\">\r\n");
      out.write("                    <span>🎉 <strong>Welcome Bonus:</strong> Get $100 free when you create your account!</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <form id=\"registerForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" method=\"POST\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"fullName\" class=\"form-label\">Full Name *</label>\r\n");
      out.write("                        <input type=\"text\" id=\"fullName\" name=\"fullName\" class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Enter your full name\" required\r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fullName != null ? fullName : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"username\" class=\"form-label\">Username *</label>\r\n");
      out.write("                        <input type=\"text\" id=\"username\" name=\"username\" class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Choose a unique username\" required\r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username != null ? username : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <div class=\"form-text\">3-20 characters, letters, numbers and underscores only</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"email\" class=\"form-label\">Email Address *</label>\r\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Enter your email address\" required\r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email != null ? email : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"phone\" class=\"form-label\">Phone Number</label>\r\n");
      out.write("                        <input type=\"tel\" id=\"phone\" name=\"phone\" class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Enter your phone number (optional)\"\r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phone != null ? phone : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"password\" class=\"form-label\">Password *</label>\r\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Create a strong password\" required>\r\n");
      out.write("                        <div class=\"form-text\">Minimum 8 characters with uppercase, lowercase, number and special character</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"confirmPassword\" class=\"form-label\">Confirm Password *</label>\r\n");
      out.write("                        <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Confirm your password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Password Strength Indicator -->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-label\">Password Strength</label>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                            <div id=\"passwordStrength\" class=\"progress-bar\" style=\"width: 0%;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"passwordStrengthText\" class=\"form-text\">Enter a password to see strength</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input type=\"checkbox\" id=\"terms\" name=\"terms\" class=\"form-check-input\" required>\r\n");
      out.write("                        <label for=\"terms\" class=\"form-check-label\">\r\n");
      out.write("                            I agree to the <a href=\"#terms\" style=\"color: var(--primary-color);\">Terms & Conditions</a>\r\n");
      out.write("                            and <a href=\"#privacy\" style=\"color: var(--primary-color);\">Privacy Policy</a> *\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input type=\"checkbox\" id=\"newsletter\" name=\"newsletter\" class=\"form-check-input\">\r\n");
      out.write("                        <label for=\"newsletter\" class=\"form-check-label\">\r\n");
      out.write("                            Subscribe to newsletter for match updates and exclusive promotions\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input type=\"checkbox\" id=\"ageConfirm\" name=\"ageConfirm\" class=\"form-check-input\" required>\r\n");
      out.write("                        <label for=\"ageConfirm\" class=\"form-check-label\">\r\n");
      out.write("                            I confirm that I am 18 years or older *\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                        Create Account & Get $100 Bonus\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-footer text-center\">\r\n");
      out.write("                <p style=\"margin: 0; color: var(--text-secondary);\">\r\n");
      out.write("                    Already have an account?\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" style=\"color: var(--primary-color); font-weight: 600; text-decoration: none;\">\r\n");
      out.write("                        Login here\r\n");
      out.write("                    </a>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Benefits Section -->\r\n");
      out.write("    <section class=\"container mt-5\">\r\n");
      out.write("        <h3 class=\"text-center mb-4\">Join the Community</h3>\r\n");
      out.write("        <div class=\"stats-grid\">\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <span class=\"stat-value\">$100</span>\r\n");
      out.write("                <span class=\"stat-label\">Welcome Bonus</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <span class=\"stat-value\">24/7</span>\r\n");
      out.write("                <span class=\"stat-label\">Live Betting</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <span class=\"stat-value\">Instant</span>\r\n");
      out.write("                <span class=\"stat-label\">Withdrawals</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <span class=\"stat-value\">98.5%</span>\r\n");
      out.write("                <span class=\"stat-label\">Payout Rate</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Social Proof -->\r\n");
      out.write("    <section class=\"container mt-5\">\r\n");
      out.write("        <div class=\"card\" style=\"background: linear-gradient(135deg, var(--primary-color), var(--secondary-color)); color: white;\">\r\n");
      out.write("            <div class=\"card-body text-center\">\r\n");
      out.write("                <h4 style=\"margin-bottom: 1rem;\">Join 10,000+ Happy Bettors</h4>\r\n");
      out.write("                <div class=\"d-flex justify-content-center\" style=\"gap: 2rem; flex-wrap: wrap;\">\r\n");
      out.write("                    <div style=\"text-align: center;\">\r\n");
      out.write("                        <div style=\"font-size: 2rem; font-weight: 700;\">⭐⭐⭐⭐⭐</div>\r\n");
      out.write("                        <div style=\"font-size: 0.9rem;\">4.8/5 Rating</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"text-align: center;\">\r\n");
      out.write("                        <div style=\"font-size: 2rem; font-weight: 700;\">🏆</div>\r\n");
      out.write("                        <div style=\"font-size: 0.9rem;\">Best E-Sports Platform</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"text-align: center;\">\r\n");
      out.write("                        <div style=\"font-size: 2rem; font-weight: 700;\">🔒</div>\r\n");
      out.write("                        <div style=\"font-size: 0.9rem;\">Bank-Level Security</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Testimonials -->\r\n");
      out.write("    <section class=\"container mt-5\">\r\n");
      out.write("        <h3 class=\"text-center mb-4\">What Our Users Say</h3>\r\n");
      out.write("        <div class=\"stats-grid\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <div style=\"color: var(--warning-color); margin-bottom: 1rem;\">⭐⭐⭐⭐⭐</div>\r\n");
      out.write("                    <p style=\"margin-bottom: 1rem; color: var(--text-secondary);\">\r\n");
      out.write("                        \"Amazing platform! The live betting feature is incredible and payouts are always instant.\r\n");
      out.write("                        Won $500 last week on the MPL finals!\"\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div style=\"font-weight: 600; color: var(--text-primary);\">- GameMaster2024</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <div style=\"color: var(--warning-color); margin-bottom: 1rem;\">⭐⭐⭐⭐⭐</div>\r\n");
      out.write("                    <p style=\"margin-bottom: 1rem; color: var(--text-secondary);\">\r\n");
      out.write("                        \"Best odds in the market and the mobile app works perfectly. Customer support is also very helpful.\r\n");
      out.write("                        Highly recommended!\"\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div style=\"font-weight: 600; color: var(--text-primary);\">- ProGamer_PH</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <div style=\"color: var(--warning-color); margin-bottom: 1rem;\">⭐⭐⭐⭐⭐</div>\r\n");
      out.write("                    <p style=\"margin-bottom: 1rem; color: var(--text-secondary);\">\r\n");
      out.write("                        \"The welcome bonus really helped me get started. Interface is clean and easy to use.\r\n");
      out.write("                        Perfect for Mobile Legends betting!\"\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div style=\"font-weight: 600; color: var(--text-primary);\">- EsportsEnthusiast</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h5>About ML Betting</h5>\r\n");
      out.write("                    <p>The premier platform for Mobile Legends Professional League betting. Experience the excitement of e-sports with secure, fair, and transparent betting.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h5>Getting Started</h5>\r\n");
      out.write("                    <div style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Home</a>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/matches/upcoming\">Browse Matches</a>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Login</a>\r\n");
      out.write("                        <a href=\"#help\">How to Bet</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h5>Support</h5>\r\n");
      out.write("                    <div style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\r\n");
      out.write("                        <a href=\"#help\">Help Center</a>\r\n");
      out.write("                        <a href=\"#contact\">24/7 Live Chat</a>\r\n");
      out.write("                        <a href=\"#responsible\">Responsible Gaming</a>\r\n");
      out.write("                        <a href=\"#terms\">Terms & Conditions</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h5>Security & Trust</h5>\r\n");
      out.write("                    <p>Your data and funds are protected with industry-standard security measures.</p>\r\n");
      out.write("                    <div style=\"margin-top: 1rem;\">\r\n");
      out.write("                        <span class=\"badge badge-success\">SSL Secured</span>\r\n");
      out.write("                        <span class=\"badge badge-primary\">Licensed</span>\r\n");
      out.write("                        <span class=\"badge badge-warning\">Audited</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("                <p>&copy; 2024 ML Betting Platform. All rights reserved. |\r\n");
      out.write("                   <span class=\"text-warning\">Please bet responsibly. 18+ only.</span>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Alert Container -->\r\n");
      out.write("    <div class=\"alert-container\"></div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Scripts -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Password strength checker\r\n");
      out.write("        document.getElementById('password').addEventListener('input', function() {\r\n");
      out.write("            const password = this.value;\r\n");
      out.write("            const strengthBar = document.getElementById('passwordStrength');\r\n");
      out.write("            const strengthText = document.getElementById('passwordStrengthText');\r\n");
      out.write("\r\n");
      out.write("            let score = 0;\r\n");
      out.write("            let feedback = [];\r\n");
      out.write("\r\n");
      out.write("            // Length check\r\n");
      out.write("            if (password.length >= 8) score += 25;\r\n");
      out.write("            else feedback.push('at least 8 characters');\r\n");
      out.write("\r\n");
      out.write("            // Uppercase check\r\n");
      out.write("            if (/[A-Z]/.test(password)) score += 25;\r\n");
      out.write("            else feedback.push('uppercase letter');\r\n");
      out.write("\r\n");
      out.write("            // Lowercase check\r\n");
      out.write("            if (/[a-z]/.test(password)) score += 25;\r\n");
      out.write("            else feedback.push('lowercase letter');\r\n");
      out.write("\r\n");
      out.write("            // Number check\r\n");
      out.write("            if (/\\d/.test(password)) score += 25;\r\n");
      out.write("            else feedback.push('number');\r\n");
      out.write("\r\n");
      out.write("            // Special character check\r\n");
      out.write("            if (/[!@#$%^&*(),.?\":{}|<>]/.test(password)) score += 25;\r\n");
      out.write("            else feedback.push('special character');\r\n");
      out.write("\r\n");
      out.write("            // Update progress bar\r\n");
      out.write("            strengthBar.style.width = Math.min(score, 100) + '%';\r\n");
      out.write("\r\n");
      out.write("            // Update color and text\r\n");
      out.write("            if (score === 0) {\r\n");
      out.write("                strengthBar.style.background = 'var(--text-muted)';\r\n");
      out.write("                strengthText.textContent = 'Enter a password to see strength';\r\n");
      out.write("                strengthText.style.color = 'var(--text-muted)';\r\n");
      out.write("            } else if (score < 50) {\r\n");
      out.write("                strengthBar.style.background = 'var(--danger-color)';\r\n");
      out.write("                strengthText.textContent = 'Weak - Add: ' + feedback.join(', ');\r\n");
      out.write("                strengthText.style.color = 'var(--danger-color)';\r\n");
      out.write("            } else if (score < 75) {\r\n");
      out.write("                strengthBar.style.background = 'var(--warning-color)';\r\n");
      out.write("                strengthText.textContent = 'Fair - Add: ' + feedback.join(', ');\r\n");
      out.write("                strengthText.style.color = 'var(--warning-color)';\r\n");
      out.write("            } else if (score < 100) {\r\n");
      out.write("                strengthBar.style.background = 'var(--secondary-color)';\r\n");
      out.write("                strengthText.textContent = 'Good - Add: ' + feedback.join(', ');\r\n");
      out.write("                strengthText.style.color = 'var(--secondary-color)';\r\n");
      out.write("            } else {\r\n");
      out.write("                strengthBar.style.background = 'var(--success-color)';\r\n");
      out.write("                strengthText.textContent = 'Excellent password strength!';\r\n");
      out.write("                strengthText.style.color = 'var(--success-color)';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Confirm password validation\r\n");
      out.write("        document.getElementById('confirmPassword').addEventListener('input', function() {\r\n");
      out.write("            const password = document.getElementById('password').value;\r\n");
      out.write("            const confirmPassword = this.value;\r\n");
      out.write("\r\n");
      out.write("            if (confirmPassword && password !== confirmPassword) {\r\n");
      out.write("                this.style.borderColor = 'var(--danger-color)';\r\n");
      out.write("                this.style.boxShadow = '0 0 0 3px rgba(225, 112, 85, 0.1)';\r\n");
      out.write("            } else {\r\n");
      out.write("                this.style.borderColor = 'var(--border-color)';\r\n");
      out.write("                this.style.boxShadow = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Form validation before submit\r\n");
      out.write("        document.getElementById('registerForm').addEventListener('submit', function(e) {\r\n");
      out.write("            const password = document.getElementById('password').value;\r\n");
      out.write("            const confirmPassword = document.getElementById('confirmPassword').value;\r\n");
      out.write("\r\n");
      out.write("            // Check password match\r\n");
      out.write("            if (password !== confirmPassword) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                showAlert('Passwords do not match!', 'danger');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Check password strength\r\n");
      out.write("            if (!isPasswordStrong(password)) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                showAlert('Please use a stronger password with at least 8 characters including uppercase, lowercase, number and special character.', 'danger');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Check terms acceptance\r\n");
      out.write("            if (!document.getElementById('terms').checked) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                showAlert('Please accept the Terms & Conditions to continue.', 'danger');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Check age confirmation\r\n");
      out.write("            if (!document.getElementById('ageConfirm').checked) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                showAlert('You must be 18 or older to create an account.', 'danger');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Show loading state\r\n");
      out.write("            const submitBtn = this.querySelector('button[type=\"submit\"]');\r\n");
      out.write("            setButtonLoading(submitBtn, true);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Username availability check (simulated)\r\n");
      out.write("        document.getElementById('username').addEventListener('blur', function() {\r\n");
      out.write("            const username = this.value;\r\n");
      out.write("            if (username.length >= 3) {\r\n");
      out.write("                // Simulate API call\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    // For demo purposes, show username as available\r\n");
      out.write("                    showAlert('Username \"' + username + '\" is available!', 'success');\r\n");
      out.write("                }, 500);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /register.jsp(42,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMessage}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                    <div class=\"alert alert-danger\">\r\n");
        out.write("                        <span>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\r\n");
        out.write("                    </div>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
